name: Build Debian Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install stdeb and build tools
        run: |
          python -m pip install --upgrade pip
          pip install stdeb setuptools

      - name: Build Debian package
        run: |
          cd src
          python setup.py --command-packages=stdeb.command bdist_deb

      - name: Upload .deb to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: src/deb_dist/*.deb
