name: Publish to PyPI on mdllama.py Update

on:
  push:
    paths:
      - 'mdllama.py'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI with Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
