name: Publish to PyPI on mdllama.py Update

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update RELEASE on GitHub Release"]
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        working-directory: src
        run: python -m build

      - name: Validate package
        working-directory: src
        run: |
          python -m twine check dist/*
          # Test that the package can be imported
          pip install dist/*.whl
          python -c "import mdllama; print('Package import successful')"
          mdllama --version

      - name: Publish to PyPI with Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: src/dist