name: Sync README to src/

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy README.md to src/
        run: cp README.md src/README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Sync README.md to src/ on README update [Actions]
          file_pattern: src/README.md
