name: Trigger PPA Build on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger-ppa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-and-publish-ppa.yml in packages repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PACKAGES_REPO_TOKEN }}
          repository: QinCai-rui/packages
          event-type: build-and-publish-ppa
          client-payload: '{"ref": "${{ github.ref }}", "release_tag": "${{ github.event.release.tag_name }}"}'
